const { chromium } = require('playwright');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const origin = process.env.PREVIEW_ORIGIN || 'http://127.0.0.1:4173';
(async () => {
  const browser = await chromium.launch({channel:'msedge',headless:true});
  const context = await browser.newContext({viewport:{width:1440,height:1100},reducedMotion:'reduce'});
  const page = await context.newPage();
  const errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  fs.mkdirSync('mockups/previews',{recursive:true});
  for(const design of ['gallery','workspace','cinema']) {
    await page.goto(`${origin}/mockups/${design}.html`);
    await page.evaluate(()=>localStorage.clear());
    await page.reload();
    assert.equal(await page.locator('.project').count(),14);
    assert.equal(await page.locator('.project-group').count(),5);
    assert.equal(await page.locator('#side-categories [data-category="Archives"] .count').innerText(),'1');
    assert.equal(await page.locator('#side-categories [data-category="Utilities"] .count').innerText(),'2');
    await page.locator('.project [data-pin="sudoku"]').click();
    assert.equal(await page.locator('#favorites-list .favorite').count(),1);
    await page.reload();
    assert.equal(await page.locator('#favorites-list .favorite').count(),1,'Pin persists after reload');
    const filters=design!=='gallery' ? '#side-categories' : '#categories';
    await page.locator(`${filters} [data-category="Archives"]`).click();
    assert.equal(await page.locator('.project').count(),1);
    assert.match(await page.locator('.project').innerText(),/Guangzhou/);
    await page.locator(`${filters} [data-category="Travel"]`).click();
    assert.equal(await page.locator('.project').count(),1);
    assert.equal(await page.locator('#favorites-list .favorite').count(),1,'Pins unaffected by category filter');
    await page.locator(`${filters} [data-category="All apps"]`).click();
    await page.locator(`${filters} [data-category="Utilities"]`).click();
    assert.equal(await page.locator('.project').count(),2);
    assert.match(await page.locator('.project').last().innerText(),/Expense Tracker/);
    await page.locator(`${filters} [data-category="All apps"]`).click();
    await page.getByRole('searchbox').fill('zzzz-no-app');
    assert.equal(await page.locator('.project').count(),0);
    await page.locator('[data-reset]').click();
    await page.getByRole('searchbox').fill('leaflet');
    assert.equal(await page.locator('.project').count(),1);
    await page.getByRole('searchbox').fill('');
    await page.locator('.project [data-detail="menu-planner"]').first().click();
    assert.equal(await page.locator('dialog[open]').count(),1);
    assert.match(await page.locator('#detail-content').innerText(),/What I learnt/);
    await page.locator('dialog [data-pin="menu-planner"]').click();
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('dialog[open]').count(),0);
    assert.equal(await page.locator('#favorites-list .favorite').count(),2);
    if(design==='cinema') {
      await page.getByRole('button',{name:'Next app',exact:true}).click();
      assert.equal(await page.locator('h1').innerText(),'Expense Tracker');
      await page.getByRole('button',{name:'Previous app',exact:true}).click();
      assert.equal(await page.locator('h1').innerText(),'Menu Planner');
      await page.locator('[data-feature="chinese-practice"]').click();
      await page.getByRole('button',{name:'Previous app',exact:true}).click();
      assert.match(await page.locator('h1').innerText(),/Guangzhou/);
      await page.keyboard.press('ArrowRight');
      assert.equal(await page.locator('h1').innerText(),'Chinese Learning App');
      for(const theme of ['coral','mulberry','mineral']) {
        await page.locator(`[data-theme-choice="${theme}"]`).click();
        await page.reload();
        assert.equal(await page.locator('body').getAttribute('data-theme'),theme);
        assert.equal(await page.locator(`[data-theme-choice="${theme}"]`).getAttribute('aria-pressed'),'true');
        await page.screenshot({path:`mockups/previews/cinema-${theme}.jpg`,type:'jpeg',quality:90});
      }
      assert.ok(await page.locator('.sidebar').isVisible());
      assert.match(await page.locator('.brand').innerText(),/Yiwen[\s\S]*GoatedApps/);
      await page.locator('[data-feature="beijing-itinerary"]').click();assert.equal(await page.locator('h1').innerText(),'Beijing Trip Itinerary');await page.locator('[data-feature="menu-planner"]').click();}
    await page.locator('#favorites-list [data-pin="sudoku"]').click();
    await page.locator('#favorites-list [data-pin="menu-planner"]').click();
    await page.locator('.toast').evaluate(element=>element.classList.remove('visible'));
    await page.evaluate(()=>window.scrollTo(0,0));
    await page.screenshot({path:`mockups/previews/${design}.jpg`,type:'jpeg',quality:90});
    await page.setViewportSize({width:390,height:844});
    await page.evaluate(()=>window.scrollTo(0,0));
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'No mobile horizontal overflow');
    await page.screenshot({path:`mockups/previews/${design}-mobile.jpg`,type:'jpeg',quality:85,fullPage:true});
    if(design==='cinema') {
      assert.equal(await page.locator('.sidebar').isVisible(),false);
      await page.getByRole('button',{name:'Next app',exact:true}).click();
      assert.equal(await page.locator('h1').innerText(),'Expense Tracker');
      await page.locator('[data-theme-choice="mulberry"]').click();
      assert.equal(await page.locator('body').getAttribute('data-theme'),'mulberry');
    }
    await page.locator('.project [data-detail="menu-planner"]').first().click();
    assert.equal(await page.locator('dialog[open]').count(),1);
    await page.keyboard.press('Escape');
    for(const img of await page.locator('.project img').all()) {await img.scrollIntoViewIfNeeded(); await img.evaluate(el=>el.decode());}
    await page.setViewportSize({width:1440,height:1100});
    console.log(`${design}: passed pin persistence, category/search, detail dialog, mobile layout and image loading`);
  }
  await page.goto(`${origin}/mockups/gallery.html`);
  await page.locator('.project [data-pin="sudoku"]').click();
  await page.goto(`${origin}/mockups/workspace.html`);
  assert.equal(await page.locator('#favorites-list .favorite').count(),1,'Pins shared across concepts');
  await page.evaluate(()=>localStorage.setItem('yiwen-frequently-used-v1','broken json'));
  await page.reload();
  assert.equal(await page.locator('.project').count(),14,'Corrupt preferences do not break browsing');
  await page.evaluate(()=>localStorage.clear());
  await page.goto(`${origin}/mockups/index.html`);
  for(const img of await page.locator('img').all()) await img.evaluate(el=>el.decode());
  await page.screenshot({path:'mockups/previews/comparison.jpg',type:'jpeg',quality:90,fullPage:true});
  await page.goto(`${origin}/`);
  assert.equal(await page.locator('.project').count(),14,'Homepage shows all apps');
  assert.equal(await page.locator('.sidebar').isVisible(),true,'Homepage shows category sidebar');
  assert.equal(await page.locator('.compare').isVisible(),false,'Homepage hides mockup comparison');
  assert.equal(await page.locator('.project img').count(),14,'Homepage resolves all screenshots');
  for(const img of await page.locator('.project img').all()) await img.evaluate(el=>el.decode());
  await page.locator('#side-categories [data-category="Archives"]').click();
  assert.match(await page.locator('.project').innerText(),/Guangzhou/);
  await page.locator('#side-categories [data-category="Utilities"]').click();
  assert.match(await page.locator('.project').last().innerText(),/Expense Tracker/);
  const blocked = await browser.newContext();
  await blocked.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw new DOMException('Blocked','SecurityError');}});});
  const blockedPage=await blocked.newPage();
  await blockedPage.goto(`${origin}/mockups/gallery.html`);
  await blockedPage.locator('.project [data-pin="sudoku"]').click();
  assert.equal(await blockedPage.locator('#favorites-list .favorite').count(),1,'Session pin works with blocked storage');
  assert.equal(await blockedPage.locator('#save-note').innerText(),'Saved for this visit only');
  assert.deepEqual(errors,[],'No browser JavaScript errors');
  console.log('Passed shared preferences, corrupt/blocked storage and comparison previews.');
  await browser.close();
})().catch(error=>{console.error(error);process.exit(1);});
